[tool.isort]
profile="black"
skip_gitignore=true

[tool.mypy]
strict=true
disable_error_code="override"
files = [
    "src",
    "tests",
    "scripts",
    "extract_metadata"
]
no_namespace_packages=true

[tool.pytest.ini_options]
pythonpath = "src"
